version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mikelorant-open-webui_server_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  server:
    image: ghcr.io/open-webui/open-webui:0.5.3
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/backend/data
